# Generated by Django 4.1.4 on 2023-01-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=8)),
                ('contact', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=45)),
                ('accesslable', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='qualifications',
            fields=[
                ('qualifications', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('skills', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('qualifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qualifications')),
                ('skills', models.ManyToManyField(to='app.skills')),
            ],
        ),
    ]
