# Generated by Django 4.1.3 on 2023-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidatedetails_date_alter_candidatedetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetails',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='skills',
            field=models.ManyToManyField(to='app.skills'),
        ),
    ]
