# Generated by Django 4.1.3 on 2023-01-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_candidatedetails_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetails',
            name='date',
        ),
    ]
