# Generated by Django 4.1.3 on 2023-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_candidatedetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
