# Generated by Django 4.1.3 on 2023-01-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidatedetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetails',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='skills',
            field=models.ManyToManyField(to='app.skills'),
        ),
    ]
