# Generated by Django 4.1.4 on 2023-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_candidatedetails_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('first_name', models.CharField(default='Default', max_length=30)),
                ('last_name', models.CharField(default='Default', max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.CharField(default='Default', max_length=15)),
                ('role', models.CharField(default='Default', max_length=20)),
                ('accesslable', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='appuser',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
